<?php defined("APP") or die() // Main Page ?>
<section class="section-featured">
    <svg id="heroback">
        <defs>
            <linearGradient id="grad1" x1="0%" y1="0%" x2="80%" y2="0%">
                <stop offset="0%" style="stop-color:var(--color-stop-1);stop-opacity:1" />
                <stop offset="100%" style="stop-color:var(--color-stop-2);stop-opacity:1" />
            </linearGradient>
        </defs>
        <path d="M 1049.9932250976562 253.27206420898438 C 1049.9932250976562 464.46495701693016 927.4027099609375 1071.3050537109375 747.8369750976562 946.8558349609375 C 646.2172241210938 876.427490234375 192.1222686767578 729.349609375 187.61318969726562 528.688720703125 C 183.61166381835938 350.6175842285156 19.458803176879883 269.17242431640625 63.39866638183594 55.160675048828125 C 95.57649230957031 -101.56306457519531 1049.9932250976562 42.07917140103859 1049.9932250976562 253.27206420898438 Z" stroke-width="0" stroke="#000000" fill="url(#grad1)" transform="matrix(1 0 0 1 -20.2864 -92.3031)"></path>
    </svg>
    <svg id="hero">
        <defs>
            <linearGradient id="grad2" x1="0%" y1="0%" x2="80%" y2="0%">
                <stop offset="0%" style="stop-color:var(--color-stop-1);stop-opacity:1" />
                <stop offset="100%" style="stop-color:var(--color-stop-2);stop-opacity:1" />
            </linearGradient>
        </defs>
        <path d="M 1049.9932250976562 253.27206420898438 C 1049.9932250976562 464.46495701693016 927.4027099609375 1071.3050537109375 747.8369750976562 946.8558349609375 C 646.2172241210938 876.427490234375 192.1222686767578 729.349609375 187.61318969726562 528.688720703125 C 183.61166381835938 350.6175842285156 19.458803176879883 269.17242431640625 63.39866638183594 55.160675048828125 C 95.57649230957031 -101.56306457519531 1049.9932250976562 42.07917140103859 1049.9932250976562 253.27206420898438 Z" stroke-width="0" stroke="#000000" fill="url(#grad2)" transform="matrix(1 0 0 1 -20.2864 -92.3031)"></path>
    </svg>
    <div class="container">
        <div class="row">
            <div class="col-md-7">

                <h2><?php echo e("Become an InstaUrl.me Affiliate:<br> ") ?> </h2>
                <p><?php echo e("Our program pays you up to 30% of every sale, and recurring payments generated by your referrals during the lifetime of their membership!") ?></p>


                <a href="#apply-now" class="btn btn-primary"><?php echo e("Apply Now") ?></a>
                <a href="#mainto" class="btn btn-transparent scroll"><?php echo e("Learn more") ?></a>
            </div>
        </div>
    </div>
</section>
<section class="section-secondary" id="mainto">
    <?php testimonialsItems() ?>
    <div class="container">
        <h3 class="text-center feature-h">
            <?php echo e("Program Benefits ") ?>
        </h3>
        <p class=" feature-p">
            <?php echo e("A Affiliate is a powerful marketing tool when you use it carefully. It is not just a link but a medium between your customer and their destination. A short link allows you to collect so much data about your customers and their behaviors.") ?>
        </p>
        <p class=" feature-p">
            <?php echo e("1) Build Residual Income With 30% Recurring Commission.") ?>
        </p>
        <p class=" feature-p">
            <?php echo e("2) 30 Day Cookie.") ?>
        </p>
        <p class=" feature-p">
            <?php echo e("3) Offer FREE Trials.") ?>
        </p>
        <p class=" feature-p">
            <?php echo e("4) Comprehensive Affiliate Resource Library 5) Promote a Product With Endless Uses & Potential Customers.") ?>
        </p>

    </div>
</section>



<section id="apply-now">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="centered form full-width">
                    <?php echo Main::message() ?>
                    <form role="form" class="live_form" method="post" action="<?php echo Main::href("affiliate")?>">
                        <h3><?php echo e("Apply For Our Affiliate Progra") ?></h3>
                        <p><?php echo e("Please complete the application below to join our affiliate program."); ?></p>
                        <div class="form-group">
                            <label for="name"><?php echo e(" First and Last Name") ?>(<?php echo e("Required") ?>)</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="<?php echo e("Name") ?>" value="<?php echo ($this->logged() ? $this->user->username : "") ?>" required>
                        </div>
                        <div class="form-group">
                            <label for="email"><?php echo e("Email") ?> (<?php echo e("Required") ?>)</label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="<?php echo e("Email") ?>" value="<?php echo ($this->logged() ? $this->user->email : "") ?>" required>
                        </div>
                        <div class="form-group">
                            <label for="website"><?php echo e("List and Describe Websites & Social Media Profiles/Platforms you plan on using to promote our service") ?> (<?php echo e("Required") ?>)</label>
                            <input type="text" class="form-control" name="website_brand" id="website" placeholder="<?php echo e("Website/Brand") ?>" value="<?php echo ($this->logged() ? $this->user->email : "") ?>" required>
                        </div>

                        <div class="form-group">
                            <label for="paypal"><?php echo e("PayPal account for payments") ?>(<?php echo e("Required") ?>)</label>
                            <input type="email" class="form-control" name="paypal_account" id="paypal" placeholder="<?php echo e("Paypal Account") ?>" value="<?php echo ($this->logged() ? $this->user->email : "") ?>" required>
                        </div>

                        <div class="form-group">
                            <label for="affiliate_link"><?php echo e("Affiliate ID") ?></label>
                            <input type="text" class="form-control" name="affiliate_link" id="affiliate_link" placeholder="<?php echo e("Paypal Account") ?>" value="<?php echo ($this->logged() ? $this->user->email : "") ?>" required>
                        </div>

                        <div class="form-group">
                            <label>
                                <input type="checkbox" name="terms" value="1" data-class="aero" required>
                                <span class="check-box"><?php echo e("I agree to the")?> <a href="<?php echo $this->config["url"] ?>/page/terms" target="_blank"><?php echo e("terms and conditions")?></a>.</span>
                            </label>
                        </div>
                        <p><?php echo Main::captcha() ?></p>
                        <?php echo Main::csrf_token(TRUE) ?>
                        <div class="submit-button">
                            <button type="submit" class="btn btn-primary btn-round"><?php echo e("Apply for Affiliate") ?></button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</section>
